import type { Evidence, UserProfile } from "./types";

export const SEED_PROFILE: UserProfile = {
  fullName: "",
  occupation: "",
  yearsInBusiness: "",
  location: "",
};

export const SEED_EVIDENCE: Evidence[] = [
  {
    id: "ev-01",
    category: "repayment",
    dimension: "repayment",
    label: "Loan Repayment Receipt",
    filename: "loan_repayment_receipt_2026.pdf",
    fileType: "PDF",
    uploadDate: "2026-07-20",
    documentDate: "2026-05-17",
    amount: 25000,
    extractedData: {
      documentType: "loan_repayment",
      issuer: "Rajasthan Gramin Bank",
      amount: 25000,
      installments: 10,
      paid: 10,
      late: 0,
      paymentStatus: "closed",
    },
    qualityLevel: "documented",
    verificationStatus: "documented",
    signalScore: 92,
    anomalyFlags: [],
  },
  {
    id: "ev-02",
    category: "repayment",
    dimension: "repayment",
    label: "MFI Installment Record",
    filename: "mfi_installment_record.pdf",
    fileType: "PDF",
    uploadDate: "2026-07-20",
    documentDate: "2026-04-02",
    amount: 18000,
    extractedData: {
      documentType: "mfi_repayment",
      issuer: "Sahyog Micro Finance",
      amount: 18000,
      installments: 12,
      paid: 12,
      late: 1,
      paymentStatus: "closed",
    },
    qualityLevel: "verified",
    verificationStatus: "verified",
    signalScore: 86,
    anomalyFlags: [],
  },
  {
    id: "ev-03",
    category: "repayment",
    dimension: "repayment",
    label: "Lender Acknowledgement Letter",
    filename: "lender_acknowledgement_letter.pdf",
    fileType: "PDF",
    uploadDate: "2026-07-21",
    documentDate: "2026-06-11",
    extractedData: { documentType: "lender_acknowledgement", issuer: "Rajasthan Gramin Bank" },
    qualityLevel: "documented",
    verificationStatus: "documented",
    signalScore: 84,
    anomalyFlags: [],
  },
  {
    id: "ev-04",
    category: "payment",
    dimension: "discipline",
    label: "Electricity Bill",
    filename: "electricity_bill_jvvnl_jun2026.jpeg",
    fileType: "JPEG",
    uploadDate: "2026-07-21",
    documentDate: "2026-06-28",
    amount: 2140,
    extractedData: {
      documentType: "electricity_bill",
      issuer: "JVVNL",
      amount: 2140,
      months: 11,
      paymentStatus: "paid",
    },
    qualityLevel: "verified",
    verificationStatus: "verified",
    signalScore: 90,
    anomalyFlags: [],
  },
  {
    id: "ev-05",
    category: "payment",
    dimension: "discipline",
    label: "Water Bill",
    filename: "water_bill_phed_may2026.jpg",
    fileType: "JPG",
    uploadDate: "2026-07-21",
    documentDate: "2026-05-30",
    amount: 480,
    extractedData: { documentType: "water_bill", issuer: "PHED Jaipur", amount: 480, months: 6, paymentStatus: "paid" },
    qualityLevel: "verified",
    verificationStatus: "verified",
    signalScore: 82,
    anomalyFlags: [],
  },
  {
    id: "ev-06",
    category: "payment",
    dimension: "discipline",
    label: "Mobile / Telecom Bill",
    filename: "telecom_bill_jun2026.pdf",
    fileType: "PDF",
    uploadDate: "2026-07-21",
    documentDate: "2026-06-15",
    amount: 799,
    extractedData: { documentType: "telecom_bill", issuer: "Airtel", amount: 799, months: 12, paymentStatus: "paid" },
    qualityLevel: "verified",
    verificationStatus: "verified",
    signalScore: 80,
    anomalyFlags: [],
  },
  {
    id: "ev-07",
    category: "payment",
    dimension: "discipline",
    label: "Shop Rent Receipt",
    filename: "shop_rent_receipt_apr2026.jpeg",
    fileType: "JPEG",
    uploadDate: "2026-07-22",
    documentDate: "2026-04-05",
    amount: 9000,
    extractedData: { documentType: "rent_receipt", issuer: "Shanti Bhawan Trust", amount: 9000, paymentStatus: "paid" },
    qualityLevel: "self_declared",
    verificationStatus: "low_quality",
    signalScore: 68,
    anomalyFlags: ["blurred_scan"],
  },
  {
    id: "ev-08",
    category: "payment",
    dimension: "discipline",
    label: "Recurring Payment Record",
    filename: "recurring_payments_summary.docx",
    fileType: "DOCX",
    uploadDate: "2026-07-22",
    documentDate: "2026-03-12",
    extractedData: { documentType: "recurring_payments", months: 9, paymentStatus: "paid" },
    qualityLevel: "documented",
    verificationStatus: "documented",
    signalScore: 76,
    anomalyFlags: [],
  },
  {
    id: "ev-09",
    category: "business",
    dimension: "continuity",
    label: "Supplier Invoice",
    filename: "supplier_invoice_agarwal_traders.pdf",
    fileType: "PDF",
    uploadDate: "2026-07-22",
    documentDate: "2026-06-20",
    amount: 64500,
    extractedData: { documentType: "supplier_invoice", issuer: "Agarwal Traders", amount: 64500, months: 8 },
    qualityLevel: "documented",
    verificationStatus: "under_review",
    signalScore: 78,
    anomalyFlags: [],
  },
  {
    id: "ev-10",
    category: "business",
    dimension: "continuity",
    label: "Wholesaler Receipt",
    filename: "wholesaler_receipt_mar2026.pdf",
    fileType: "PDF",
    uploadDate: "2026-07-22",
    documentDate: "2026-03-18",
    amount: 41200,
    extractedData: { documentType: "wholesaler_receipt", issuer: "Jaipur Wholesale Mandi", amount: 41200 },
    qualityLevel: "documented",
    verificationStatus: "documented",
    signalScore: 80,
    anomalyFlags: [],
  },
  {
    id: "ev-11",
    category: "business",
    dimension: "continuity",
    label: "Market Association Record",
    filename: "vyapar_sangh_membership.pdf",
    fileType: "PDF",
    uploadDate: "2026-07-23",
    documentDate: "2025-11-10",
    extractedData: { documentType: "association_record", issuer: "Jaipur Vyapar Sangh" },
    qualityLevel: "documented",
    verificationStatus: "documented",
    signalScore: 74,
    anomalyFlags: [],
  },
  {
    id: "ev-12",
    category: "business",
    dimension: "continuity",
    label: "Duplicate Supplier Invoice",
    filename: "supplier_invoice_agarwal_traders_copy.pdf",
    fileType: "PDF",
    uploadDate: "2026-07-23",
    documentDate: "2026-06-20",
    amount: 64500,
    extractedData: { documentType: "supplier_invoice", issuer: "Agarwal Traders", amount: 64500 },
    qualityLevel: "self_declared",
    verificationStatus: "duplicate",
    signalScore: 0,
    anomalyFlags: ["duplicate_of_ev-09"],
  },
  {
    id: "ev-13",
    category: "income",
    dimension: "income",
    label: "Monthly Sales Record",
    filename: "monthly_sales_record_q2_2026.docx",
    fileType: "DOCX",
    uploadDate: "2026-07-23",
    documentDate: "2026-06-30",
    amount: 138000,
    extractedData: { documentType: "sales_record", amount: 138000, months: 6 },
    qualityLevel: "documented",
    verificationStatus: "documented",
    signalScore: 72,
    anomalyFlags: [],
  },
  {
    id: "ev-14",
    category: "income",
    dimension: "income",
    label: "Handwritten Sales Note",
    filename: "handwritten_sales_note.jpg",
    fileType: "JPG",
    uploadDate: "2026-07-23",
    documentDate: "2026-05-04",
    extractedData: { documentType: "sales_note" },
    qualityLevel: "self_declared",
    verificationStatus: "low_quality",
    signalScore: 55,
    anomalyFlags: [],
  },
  {
    id: "ev-15",
    category: "income",
    dimension: "income",
    label: "Daily Sales Register",
    filename: "daily_sales_register.docx",
    fileType: "DOCX",
    uploadDate: "2026-07-24",
    documentDate: "2026-02-14",
    extractedData: { documentType: "sales_register" },
    qualityLevel: "self_declared",
    verificationStatus: "unreadable",
    signalScore: 0,
    anomalyFlags: [],
  },
  {
    id: "ev-16",
    category: "tax",
    dimension: "discipline",
    label: "Tax Payment Receipt",
    filename: "tax_payment_receipt_fy2025_26.pdf",
    fileType: "PDF",
    uploadDate: "2026-07-24",
    documentDate: "2026-03-28",
    amount: 11400,
    extractedData: { documentType: "tax_receipt", issuer: "Income Tax Department", amount: 11400, paymentStatus: "paid" },
    qualityLevel: "documented",
    verificationStatus: "not_verified",
    signalScore: 70,
    anomalyFlags: [],
  },
  {
    id: "ev-17",
    category: "tax",
    dimension: "continuity",
    label: "GST Filing Summary",
    filename: "gst_filing_summary_2026.pdf",
    fileType: "PDF",
    uploadDate: "2026-07-24",
    documentDate: "2026-06-10",
    extractedData: { documentType: "gst_summary", months: 8 },
    qualityLevel: "verified",
    verificationStatus: "verified",
    signalScore: 83,
    anomalyFlags: [],
  },
  {
    id: "ev-18",
    category: "asset",
    dimension: "continuity",
    label: "Refrigeration Unit Invoice",
    filename: "equipment_invoice_visicooler.pdf",
    fileType: "PDF",
    uploadDate: "2026-07-25",
    documentDate: "2026-01-22",
    amount: 46000,
    extractedData: { documentType: "equipment_invoice", issuer: "CoolTech Appliances", amount: 46000 },
    qualityLevel: "verified",
    verificationStatus: "verified",
    signalScore: 79,
    anomalyFlags: [],
  },
  {
    id: "ev-19",
    category: "asset",
    dimension: "continuity",
    label: "Two-Wheeler Registration",
    filename: "vehicle_rc_rj14.jpeg",
    fileType: "JPEG",
    uploadDate: "2026-07-25",
    documentDate: "2024-09-09",
    extractedData: { documentType: "vehicle_document", issuer: "RTO Jaipur" },
    qualityLevel: "verified",
    verificationStatus: "verified",
    signalScore: 70,
    anomalyFlags: [],
  },
  {
    id: "ev-20",
    category: "supporting",
    dimension: "income",
    label: "Income Self-Declaration",
    filename: "income_self_declaration.pdf",
    fileType: "PDF",
    uploadDate: "2026-07-25",
    documentDate: "2026-07-01",
    extractedData: { documentType: "self_declaration" },
    qualityLevel: "self_declared",
    verificationStatus: "self_declared",
    signalScore: 60,
    anomalyFlags: [],
  },
];
